name: Continuous Integration

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.11'
          cache: 'npm'

      - name: Ensure latest npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Check for Outdated Documentation
        run: |
          if [ -n "$(git status --porcelain docs/database-schema.md)" ]; then
            echo "❌ Error: The database schema is outdated."
            echo "Please run 'npm run doc:db' locally and commit the changes in docs/database-schema.md"
            exit 1
          else
            echo "✅ Documentation is up to date."
          fi

      - name: set Nx SHAs
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: 'main'

      - name: Lint check
        run: npx nx affected -t lint

      - name: Build Projects
        run: npx nx affected -t build

      - name: Run API Unit Tests
        run: npx nx test api

      - name: Run Web Unit Tests
        run: npx nx test web
